# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2
sphinx:
  configuration: docs/conf.py
formats:
  - pdf
python:
  version: 3.8
  install:
  - requirements: docs/requirements.txt
