# Generated by Django 3.1.7 on 2021-03-16 15:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("django_sql_dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboard",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2021, 3, 16, 15, 55, 41, 547103, tzinfo=utc)
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_dashboards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="edit_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="can_edit_dashboards",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="edit_policy",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("loggedin", "Logged-in users"),
                    ("group", "Users in group"),
                    ("staff", "Staff users"),
                    ("superuser", "Superusers"),
                ],
                default="private",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="view_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="can_view_dashboards",
                to="auth.group",
            ),
        ),
        migrations.AddField(
            model_name="dashboard",
            name="view_policy",
            field=models.CharField(
                choices=[
                    ("private", "Private"),
                    ("public", "Public"),
                    ("unlisted", "Unlisted"),
                    ("loggedin", "Logged-in users"),
                    ("group", "Users in group"),
                    ("staff", "Staff users"),
                    ("superuser", "Superusers"),
                ],
                default="private",
                max_length=10,
            ),
        ),
    ]
