# Generated by Django 3.2.3 on 2021-05-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_sql_dashboard", "0003_update_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dashboard",
            name="description",
            field=models.TextField(
                blank=True, help_text="Optional description (Markdown allowed)"
            ),
        ),
    ]
