# Generated by Django 3.2.8 on 2021-10-13 08:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('django_sql_dashboard', '0004_add_description_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardquery',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dashboardquery',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description (Markdown allowed)'),
        ),
        migrations.AddField(
            model_name='dashboardquery',
            name='settings',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboardquery',
            name='title',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
