# Generated by Django 3.2.8 on 2023-04-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_sql_dashboard", "0005_auto_20211013_0953"),
    ]

    operations = [
        migrations.AddField(
            model_name="dashboardquery",
            name="template",
            field=models.CharField(
                blank=True,
                help_text="Template to use for rendering this query. Leave blank to use the default template or fetch based on the column names.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="dashboardquery",
            name="settings",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Settings for this query (JSON). These settings are passed to the template.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="dashboardquery",
            name="sql",
            field=models.TextField(verbose_name="SQL query"),
        ),
    ]
